export const MECANICAS = {
  NARRACAO_DE_HISTORIAS: { id: 1, descricao: "Narração de Histórias" },
  RPG: { id: 2, descricao: "RPG" },
  PAPEL_E_CANETA: { id: 3, descricao: "Papel e Caneta" },
  ROLAGEM_DE_DADOS: { id: 4, descricao: "Rolagem de Dados" },
  CONSTRUCAO_DE_REDES_E_ROTAS: { id: 5, descricao: "Construção de Redes e Rotas" },
  JOGADORES_COM_DIFERENTES_HABILIDADES: { id: 6, descricao: "Jogadores com Diferentes Habilidades" },
  TABULEIRO_MODULAR: { id: 7, descricao: "Tabuleiro Modular" },
  ARVORES_TRILHAS_DE_TECNOLOGIA: { id: 8, descricao: "Árvores / Trilhas de Tecnologia" },
  BONUS_DE_FIM_DE_JOGO: { id: 9, descricao: "Bônus de Fim de Jogo" },
  GRADE_HEXAGONAL: { id: 10, descricao: "Grade Hexagonal" },
  SOLO_SOLITARIO: { id: 11, descricao: "Solo / Solitário" },
  ORDEM_DO_TURNO_ORDEM_DE_PASSE: { id: 12, descricao: "Ordem do Turno: Ordem de Passe" },
  PREPARACAO_VARIAVEL: { id: 13, descricao: "Preparação Variável" },
  PONTOS_DE_VITORIA_COMO_RECURSO: { id: 14, descricao: "Pontos de Vitória como Recurso" },
  RENDIMENTOS: { id: 15, descricao: "Rendimentos" },
  GERENCIAMENTO_DE_MAOS: { id: 16, descricao: "Gerenciamento de Mãos" },
  EMPRESTIMOS: { id: 17, descricao: "Empréstimos" },
  MERCADO: { id: 18, descricao: "Mercado" },
  ORDEM_DE_TURNO_BASEADO_EM_ESTATISTICAS: { id: 19, descricao: "Ordem de Turno: Baseado em Estatísticas" },
  COLOCACAO_DE_PECAS: { id: 20, descricao: "Colocação de Peças" },
  COLECIONAR_CONJUNTOS: { id: 21, descricao: "Colecionar Conjuntos" },
  MARCAS: { id: 22, descricao: "Marcas" },
  COMPRA_FECHADA: { id: 23, descricao: "Compra Fechada" },
  CONTRATOS: { id: 24, descricao: "Contratos" },
  TOMA_ESSA: { id: 25, descricao: "Toma Essa" },
  ORDEM_DO_TURNO_PROGRESSIVO: { id: 26, descricao: "Ordem do Turno: Progressivo" },
  CERCO_DE_AREA: { id: 27, descricao: "Cerco de Área" },
  COOPERATIVO: { id: 28, descricao: "Cooperativo" },
  JOGO_EM_EQUIPE: { id: 29, descricao: "Jogo em Equipe" },
  DEDUCAO: { id: 30, descricao: "Dedução" },
  SELECAO_DE_ACAO_SIMULTANEA: { id: 31, descricao: "Seleção de Ação Simultânea" },
  MOVIMENTO_EM_GRADES: { id: 32, descricao: "Movimento em Grades" },
  FILA_DE_ACOES: { id: 33, descricao: "Fila de Ações" },
  RECUPERACAO_DE_ACAO: { id: 34, descricao: "Recuperação de Ação" },
  RESOLUCAO_DE_CONFLITOS_POR_CARTAS: { id: 35, descricao: "Resolução de Conflitos por Cartas" },
  COMUNICACAO_LIMITADA: { id: 36, descricao: "Comunicação Limitada" },
  ACERTOS_E_FALHAS_CRITICAS: { id: 37, descricao: "Acertos e Falhas Críticas" },
  CENARIO_MISSAO_CAMPANHA: { id: 38, descricao: "Cenário / Missão / Campanha" },
  CONSTRUCAO_DE_BARALHO_BOLSAS_E_PECAS: { id: 39, descricao: "Construção de Baralho, Bolsas e Peças" },
  LINHA_DE_VISAO: { id: 40, descricao: "Linha de Visão" },
  HABILIDADES_1_VEZ_POR_PARTIDA: { id: 41, descricao: "Habilidades 1 vez por Partida" },
  CAMPANHA_BATALHAS_DIRIGIDAS_POR_CARTAS: { id: 42, descricao: "Campanha / Batalhas Dirigidas por Cartas" },
  LEGADO: { id: 43, descricao: "Legado" },
  ACAO_EVENTO: { id: 44, descricao: "Ação / Evento" },
  ESCOLHA_NARRATIVA: { id: 45, descricao: "Escolha Narrativa" },
  MAPA_MODIFICACAO: { id: 46, descricao: "Mapa: Modificação" },
  MARCADORES_DE_ORDENS: { id: 47, descricao: "Marcadores de Ordens" },
  FORCE_SUA_SORTE: { id: 48, descricao: "Force sua sorte" },
  VALORIZACAO_DOS_RECURSOS_NAO_ESCOLHIDOS: { id: 49, descricao: "Valorização dos Recursos Não Escolhidos" },
  PROPRIEDADE: { id: 50, descricao: "Propriedade" },
  MOVIMENTO_EM_TRILHA: { id: 51, descricao: "Movimento em Trilha" },
  NEGOCIACAO: { id: 52, descricao: "Negociação" },
  ORDEM_DE_FASES_VARIAVEL: { id: 53, descricao: "Ordem de Fases Variável" },
  VOTACAO: { id: 54, descricao: "Votação" },
  IMPULSO_DE_AREA: { id: 55, descricao: "Impulso de Área" },
  INFLUENCIA_MAIORIA_NA_AREA: { id: 56, descricao: "Influência / Maioria na Área" },
  SEGUIR_ACAO: { id: 57, descricao: "Seguir Ação" },
  REI_DA_COLINA: { id: 58, descricao: "Rei da Colina" },
  CORRIDA: { id: 59, descricao: "Corrida" },
  SELECAO_DE_ACAO: { id: 60, descricao: "Seleção de Ação" },
  CAMADAS_DE_COMPONENTES: { id: 61, descricao: "Camadas de Componentes" },
  COMPRA_ABERTA: { id: 62, descricao: "Compra Aberta" },
  CABO_DE_GUERRA: { id: 63, descricao: "Cabo-de-Guerra" },
  FIM_POR_MORTE_SUBITA: { id: 64, descricao: "Fim por Morte Súbita" },
  CARTAS_MULTIUSO: { id: 65, descricao: "Cartas Multiuso" },
  MOVIMENTO_DE_AREA: { id: 66, descricao: "Movimento de Área" },
  RESOLUCAO_POR_SIMBOLOS_NOS_DADOS: { id: 67, descricao: "Resolução por Símbolos nos Dados" },
  COMPRA_FUTURA: { id: 68, descricao: "Compra Futura" },
  EVENTOS: { id: 69, descricao: "Eventos" },
  MOVIMENTO_OCULTO: { id: 70, descricao: "Movimento Oculto" },
  ALOCACAO_DE_DIFERENTES_TIPOS_DE_TRABALHADORES: { id: 71, descricao: "Alocação de Diferentes Tipos de Trabalhadores" },
  ALOCACAO_DE_TRABALHADORES: { id: 72, descricao: "Alocação de Trabalhadores" },
  COMPROMETER_FORCAS: { id: 73, descricao: "Comprometer Forças" },
  CONSTRUCAO_A_PARTIR_DE_MODELO: { id: 74, descricao: "Construção a partir de Modelo" },
  ALOCACAO_DE_TRABALHADORES_COM_DADOS: { id: 75, descricao: "Alocação de Trabalhadores com Dados" },
  COBERTURA_DE_GRADE: { id: 76, descricao: "Cobertura de Grade" },
  ENCADEAMENTO: { id: 77, descricao: "Encadeamento" },
  RESOLUCAO_COM_TESTES_DE_ESTATISTICAS: { id: 78, descricao: "Resolução com Testes de Estatísticas" },
  MAPA_ADICAO: { id: 79, descricao: "Mapa: Adição" },
  PONTOS_DE_VITORIA_OCULTOS: { id: 80, descricao: "Pontos de Vitória Ocultos" },
  MOVIMENTO_PONTO_A_PONTO: { id: 81, descricao: "Movimento Ponto-a-Ponto" },
  ESPECULACAO_DE_COMMODITIES: { id: 82, descricao: "Especulação de Commodities" },
  PONTOS_DE_MOVIMENTO: { id: 83, descricao: "Pontos de Movimento" },
  SIMULACAO: { id: 84, descricao: "Simulação" },
  CRESCIMENTO_AUTOMATICO_DE_RECURSOS: { id: 85, descricao: "Crescimento Automático de Recursos" },
  FICHA_DE_VANTAGEM: { id: 86, descricao: "Ficha de Vantagem" },
  ZONA_DE_CONTROLE: { id: 87, descricao: "Zona de Controle" },
  TRAIDOR: { id: 88, descricao: "Traidor" },
  PAPEIS_COM_INFORMACOES_ASSIMETRICAS: { id: 89, descricao: "Papéis com Informações Assimétricas" },
  APOSTAS_E_BLEFES: { id: 90, descricao: "Apostas e Blefes" },
  SEMI_COOPERATIVO: { id: 91, descricao: "Semi-Cooperativo" },
  LEILAO_LANCES: { id: 92, descricao: "Leilão / Lances" },
  MANCALA: { id: 93, descricao: "Mancala" },
  LEILAO_LANCES_RESTRITOS: { id: 94, descricao: "Leilão: Lances Restritos" },
  GRADE_COM_QUADRADOS: { id: 95, descricao: "Grade com Quadrados" },
  ORDEM_DO_TURNO_LEILAO: { id: 96, descricao: "Ordem do Turno: Leilão" },
  COMBINACAO: { id: 97, descricao: "Combinação" },
  PONTOS_DE_ACAO: { id: 98, descricao: "Pontos de Ação" },
  ELIMINACAO_DE_JOGADORES: { id: 99, descricao: "Eliminação de Jogadores" },
  RECURSO_PARA_MOVER: { id: 100, descricao: "Recurso para Mover" },
  PEGUE_O_LIDER: { id: 101, descricao: "Pegue o Líder" },
  MOVER_SE_PELO_BARALHO: { id: 102, descricao: "Mover-se pelo Baralho" },
  ORDEM_DO_TURNO_ACAO_DE_REIVINDICACAO: { id: 103, descricao: "Ordem do Turno: Ação de Reivindicação" },
  LEILAO_LANCE_UNICO: { id: 104, descricao: "Leilão: Lance Único" },
  CRIACAO_DE_BARALHO: { id: 105, descricao: "Criação de Baralho" },
  CONEXOES: { id: 106, descricao: "Conexões" },
  INVESTIMENTO: { id: 107, descricao: "Investimento" },
  PEGAR_E_ENTREGAR: { id: 108, descricao: "Pegar e Entregar" },
  ESCALADA: { id: 109, descricao: "Escalada" },
  PONTUAR_E_REINICIAR: { id: 110, descricao: "Pontuar e Reiniciar" },
  PAPEIS_OCULTOS: { id: 111, descricao: "Papéis Ocultos" },
  RONDEL: { id: 112, descricao: "Rondel" },
  MOVER_VARIAS_UNIDADES: { id: 113, descricao: "Mover Várias Unidades" },
  MEMORIA: { id: 114, descricao: "Memória" },
  PASSAR_FICHA_DE_ACAO: { id: 115, descricao: "Passar Ficha de Ação" },
  ALIANCAS: { id: 116, descricao: "Alianças" },
  SUPORTE_SEM_RECOMPENSA: { id: 117, descricao: "Suporte sem Recompensa" },
  LEILAO_ORDEM_DO_TURNO_ATE_PASSAR: { id: 118, descricao: "Leilão: Ordem do Turno até Passar" },
  MOVIMENTO_DIRECIONADO: { id: 119, descricao: "Movimento Direcionado" },
  MERCADO_DE_ACOES: { id: 120, descricao: "Mercado de Ações" },
  MOVIMENTO_PROGRAMADO: { id: 121, descricao: "Movimento Programado" },
  ACORDOS: { id: 122, descricao: "Acordos" },
  LEILAO_LANCE_SELADO: { id: 123, descricao: "Leilão: Lance Selado" },
  POSICIONAMENTO_SECRETO: { id: 124, descricao: "Posicionamento Secreto" },
  DESLIZAR_EMPURRAR: { id: 125, descricao: "Deslizar / Empurrar" },
  SUBORNO: { id: 126, descricao: "Suborno" },
  CARTAS_DE_COMANDO: { id: 127, descricao: "Cartas de Comando" },
  CAPTURA_DE_PECAS: { id: 128, descricao: "Captura de Peças" },
  MOVIMENTO_PADRAO: { id: 129, descricao: "Movimento Padrão" },
  PISTAS_DIRECIONADAS: { id: 130, descricao: "Pistas Direcionadas" },
  MINIJOGO_NO_FINAL: { id: 131, descricao: "Minijogo no Final" },
  LEILAO_COLOCACAO_FIXA: { id: 132, descricao: "Leilão: Colocação Fixa" },
  PEDRA_PAPEL_E_TESOURA: { id: 133, descricao: "Pedra, Papel e Tesoura" },
  MULTIPLOS_MAPAS: { id: 134, descricao: "Múltiplos Mapas" },
  MOVIMENTO_TRIDIMENSIONAL: { id: 135, descricao: "Movimento Tridimensional" },
  PECAS_COMO_MAPA: { id: 136, descricao: "Peças como Mapa" },
  PERDER_A_VEZ: { id: 137, descricao: "Perder a Vez" },
  DILEMA_DO_PRISIONEIRO: { id: 138, descricao: "Dilema do Prisioneiro" },
  PRODUCAO_ALEATORIA: { id: 139, descricao: "Produção Aleatória" },
  VAZAS_TRUQUES: { id: 140, descricao: "Vazas/Truques" },
  ORDEM_DO_TURNO_TRILHA_DO_TEMPO: { id: 141, descricao: "Ordem do Turno: Trilha do Tempo" },
  ORDEM_DO_TURNO_PAPEL_OU_TIPO_DE_ACAO: { id: 142, descricao: "Ordem do Turno: Papel ou Tipo de Ação" },
  LEILAO_LOTE_MULTIPLO: { id: 143, descricao: "Leilão: Lote Múltiplo" },
  ROLAR_GIRAR_E_MOVER: { id: 144, descricao: "Rolar / Girar e Mover" },
  MAPA_REDUCAO: { id: 145, descricao: "Mapa: Redução" },
  DESENHAR: { id: 146, descricao: "Desenhar" },
  SISTEMA_DE_SORTEIO_DE_FICHAS: { id: 147, descricao: "Sistema de Sorteio de Fichas" },
  TEMPO_REAL: { id: 148, descricao: "Tempo Real" },
  LANCE_PARA_ORDEM_DE_SELECAO: { id: 149, descricao: "Lance para Ordem de Seleção" },
  MAIOR_PONTUACAO_BAIXA: { id: 150, descricao: "Maior Pontuação Baixa" },
  MOVIMENTO_COM_MODELO: { id: 151, descricao: "Movimento com Modelo" },
  BINGO: { id: 152, descricao: "Bingo" },
  DESENHO_DE_LINHAS: { id: 153, descricao: "Desenho de Linhas" },
  FUNDIR_E_ESPALHAR: { id: 154, descricao: "Fundir e Espalhar" },
  FILA_DE_RECURSOS: { id: 155, descricao: "Fila de Recursos" },
  RECONHECIMENTO_DE_PADROES: { id: 156, descricao: "Reconhecimento de Padrões" },
  APOSTAS_EM_METAS: { id: 157, descricao: "Apostas em Metas" },
  PREVISAO_DE_LANCE: { id: 158, descricao: "Previsão de Lance" },
  ROLAR_NOVAMENTE_E_BLOQUEIO: { id: 159, descricao: "Rolar Novamente e Bloqueio" },
  TORRE_DE_CUBOS: { id: 160, descricao: "Torre de Cubos" },
  MOVIMENTO_COM_DIFERENTES_DADOS: { id: 161, descricao: "Movimento com Diferentes Dados" },
  DESENHAR_ROTA_COM_PINCEL_ATOMICO: { id: 162, descricao: "Desenhar Rota com Pincel Atômico" },
  LEILAO_ECONOMIA_FECHADA: { id: 163, descricao: "Leilão: Economia Fechada" },
  LEILAO_1_RODADA: { id: 164, descricao: "Leilão: 1 Rodada" },
  LEILAO_LANCES_LIVRES: { id: 165, descricao: "Leilão: Lances Livres" },
  BATATA_QUENTE: { id: 166, descricao: "Batata Quente" },
  CORRESPONDENCIA_RAPIDA: { id: 167, descricao: "Correspondência Rápida" },
  ORDEM_DE_TURNO_INTERRUPCOES: { id: 168, descricao: "Ordem de Turno: Interrupções" },
  LEILAO_PRIORITARIO_EM_LOTE: { id: 169, descricao: "Leilão: Prioritário em Lote" },
  PARTIDA_CRONOMETRADA: { id: 170, descricao: "Partida Cronometrada" },
  ORDENACAO: { id: 171, descricao: "Ordenação" },
  EU_CORTO_VOCE_ESCOLHE: { id: 172, descricao: "Eu Corto, Você Escolhe" },
  MOVIMENTO_RELATIVO: { id: 173, descricao: "Movimento Relativo" },
  PETELECO: { id: 174, descricao: "Peteleco" },
  PERDEDOR_UNICO: { id: 175, descricao: "Perdedor Único" },
  ATUACAO_MIMICA: { id: 176, descricao: "Atuação/Mímica" },
  EMPILHAR_E_EQUILIBRAR: { id: 177, descricao: "Empilhar e Equilibrar" },
  ACAO_CRONOMETRADA: { id: 178, descricao: "Ação Cronometrada" },
  ORDEM_DO_TURNO_ALEATORIO: { id: 179, descricao: "Ordem do Turno: Aleatório" },
  LEILAO_COMPENSACAO: { id: 180, descricao: "Leilão: Compensação" },
  ORTOGRAFIA: { id: 181, descricao: "Ortografia" },
  COMPARTILHAMENTO_ENTRE_VIZINHOS: { id: 182, descricao: "Compartilhamento entre Vizinhos" },
  PERGUNTAS_E_RESPOSTAS: { id: 183, descricao: "Perguntas e Respostas" },
  REMOCAO_FISICA: { id: 184, descricao: "Remoção Física" },
  JOGADOR_JUIZ: { id: 185, descricao: "Jogador Juiz" },
  CANTAR: { id: 186, descricao: "Cantar" },
  INDUCAO: { id: 187, descricao: "Indução" },
  LEILAO_VARIOS_LOTES: { id: 188, descricao: "Leilão: Vários Lotes" },
  MOVIMENTO_POR_IMPULSO: { id: 189, descricao: "Movimento por Impulso" },
  RESOLUCAO_EM_TABULEIRO_SEPARADO: { id: 190, descricao: "Resolução em Tabuleiro Separado" },
  LEILAO_DESTREZA: { id: 191, descricao: "Leilão: Destreza" },
  TABELA_DE_PROPORCAO_PARA_COMBATE: { id: 192, descricao: "Tabela de Proporção para Combate" },
  MOVIMENTO_MEDIDO: { id: 193, descricao: "Movimento Medido" },
} as const;

export type MecanicaKey = keyof typeof MECANICAS;
export type MecanicaInfo = (typeof MECANICAS)[MecanicaKey];
export const MECANICAS_LIST = Object.values(MECANICAS);
