export const MECANICAS_MAP = {
  1: "Narração de Histórias",
  2: "RPG",
  3: "Papel e Caneta",
  4: "Rolagem de Dados",
  5: "Construção de Redes e Rotas",
  6: "Jogadores com Diferentes Habilidades",
  7: "Tabuleiro Modular",
  8: "Árvores / Trilhas de Tecnologia",
  9: "Bônus de Fim de Jogo",
  10: "Grade Hexagonal",
  11: "Solo / Solitário",
  12: "Ordem do Turno: Ordem de Passe",
  13: "Preparação Variável",
  14: "Pontos de Vitória como Recurso",
  15: "Rendimentos",
  16: "Gerenciamento de Mãos",
  17: "Empréstimos",
  18: "Mercado",
  19: "Ordem de Turno: Baseado em Estatísticas",
  20: "Colocação de Peças",
  21: "Colecionar Conjuntos",
  22: "Marcas",
  23: "Compra Fechada",
  24: "Contratos",
  25: "Toma Essa",
  26: "Ordem do Turno: Progressivo",
  27: "Cerco de Área",
  28: "Cooperativo",
  29: "Jogo em Equipe",
  30: "Dedução",
  31: "Seleção de Ação Simultânea",
  32: "Movimento em Grades",
  33: "Fila de Ações",
  34: "Recuperação de Ação",
  35: "Resolução de Conflitos por Cartas",
  36: "Comunicação Limitada",
  37: "Acertos e Falhas Críticas",
  38: "Cenário / Missão / Campanha",
  39: "Construção de Baralho, Bolsas e Peças",
  40: "Linha de Visão",
  41: "Habilidades 1 vez por Partida",
  42: "Campanha / Batalhas Dirigidas por Cartas",
  43: "Legado",
  44: "Ação / Evento",
  45: "Escolha Narrativa",
  46: "Mapa: Modificação",
  47: "Marcadores de Ordens",
  48: "Force sua sorte",
  49: "Valorização dos Recursos Não Escolhidos",
  50: "Propriedade",
  51: "Movimento em Trilha",
  52: "Negociação",
  53: "Ordem de Fases Variável",
  54: "Votação",
  55: "Impulso de Área",
  56: "Influência / Maioria na Área",
  57: "Seguir Ação",
  58: "Rei da Colina",
  59: "Corrida",
  60: "Seleção de Ação",
  61: "Camadas de Componentes",
  62: "Compra Aberta",
  63: "Cabo-de-Guerra",
  64: "Fim por Morte Súbita",
  65: "Cartas Multiuso",
  66: "Movimento de Área",
  67: "Resolução por Símbolos nos Dados",
  68: "Compra Futura",
  69: "Eventos",
  70: "Movimento Oculto",
  71: "Alocação de Diferentes Tipos de Trabalhadores",
  72: "Alocação de Trabalhadores",
  73: "Comprometer Forças",
  74: "Construção a partir de Modelo",
  75: "Alocação de Trabalhadores com Dados",
  76: "Cobertura de Grade",
  77: "Encadeamento",
  78: "Resolução com Testes de Estatísticas",
  79: "Mapa: Adição",
  80: "Pontos de Vitória Ocultos",
  81: "Movimento Ponto-a-Ponto",
  82: "Especulação de Commodities",
  83: "Pontos de Movimento",
  84: "Simulação",
  85: "Crescimento Automático de Recursos",
  86: "Ficha de Vantagem",
  87: "Zona de Controle",
  88: "Traidor",
  89: "Papéis com Informações Assimétricas",
  90: "Apostas e Blefes",
  91: "Semi-Cooperativo",
  92: "Leilão / Lances",
  93: "Mancala",
  94: "Leilão: Lances Restritos",
  95: "Grade com Quadrados",
  96: "Ordem do Turno: Leilão",
  97: "Combinação",
  98: "Pontos de Ação",
  99: "Eliminação de Jogadores",
  100: "Recurso para Mover",
  101: "Pegue o Líder",
  102: "Mover-se pelo Baralho",
  103: "Ordem do Turno: Ação de Reivindicação",
  104: "Leilão: Lance Único",
  105: "Criação de Baralho",
  106: "Conexões",
  107: "Investimento",
  108: "Pegar e Entregar",
  109: "Escalada",
  110: "Pontuar e Reiniciar",
  111: "Papéis Ocultos",
  112: "Rondel",
  113: "Mover Várias Unidades",
  114: "Memória",
  115: "Passar Ficha de Ação",
  116: "Alianças",
  117: "Suporte sem Recompensa",
  118: "Leilão: Ordem do Turno até Passar",
  119: "Movimento Direcionado",
  120: "Mercado de Ações",
  121: "Movimento Programado",
  122: "Acordos",
  123: "Leilão: Lance Selado",
  124: "Posicionamento Secreto",
  125: "Deslizar / Empurrar",
  126: "Suborno",
  127: "Cartas de Comando",
  128: "Captura de Peças",
  129: "Movimento Padrão",
  130: "Pistas Direcionadas",
  131: "Minijogo no Final",
  132: "Leilão: Colocação Fixa",
  133: "Pedra, Papel e Tesoura",
  134: "Múltiplos Mapas",
  135: "Movimento Tridimensional",
  136: "Peças como Mapa",
  137: "Perder a Vez",
  138: "Dilema do Prisioneiro",
  139: "Produção Aleatória",
  140: "Vazas/Truques",
  141: "Ordem do Turno: Trilha do Tempo",
  142: "Ordem do Turno: Papel ou Tipo de Ação",
  143: "Leilão: Lote Múltiplo",
  144: "Rolar / Girar e Mover",
  145: "Mapa: Redução",
  146: "Desenhar",
  147: "Sistema de Sorteio de Fichas",
  148: "Tempo Real",
  149: "Lance para Ordem de Seleção",
  150: "Maior Pontuação Baixa",
  151: "Movimento com Modelo",
  152: "Bingo",
  153: "Desenho de Linhas",
  154: "Fundir e Espalhar",
  155: "Fila de Recursos",
  156: "Reconhecimento de Padrões",
  157: "Apostas em Metas",
  158: "Previsão de Lance",
  159: "Rolar Novamente e Bloqueio",
  160: "Torre de Cubos",
  161: "Movimento com Diferentes Dados",
  162: "Desenhar Rota com Pincel Atômico",
  163: "Leilão: Economia Fechada",
  164: "Leilão: 1 Rodada",
  165: "Leilão: Lances Livres",
  166: "Batata Quente",
  167: "Correspondência Rápida",
  168: "Ordem de Turno: Interrupções",
  169: "Leilão: Prioritário em Lote",
  170: "Partida Cronometrada",
  171: "Ordenação",
  172: "Eu Corto, Você Escolhe",
  173: "Movimento Relativo",
  174: "Peteleco",
  175: "Perdedor Único",
  176: "Atuação/Mímica",
  177: "Empilhar e Equilibrar",
  178: "Ação Cronometrada",
  179: "Ordem do Turno: Aleatório",
  180: "Leilão: Compensação",
  181: "Ortografia",
  182: "Compartilhamento entre Vizinhos",
  183: "Perguntas e Respostas",
  184: "Remoção Física",
  185: "Jogador Juiz",
  186: "Cantar",
  187: "Indução",
  188: "Leilão: Vários Lotes",
  189: "Movimento por Impulso",
  190: "Resolução em Tabuleiro Separado",
  191: "Leilão: Destreza",
  192: "Tabela de Proporção para Combate",
  193: "Movimento Medido",
} as const;

export type MecanicaId = keyof typeof MECANICAS_MAP;

export const MECANICAS_LIST = Object.entries(MECANICAS_MAP).map(
  ([id, nome]) => ({ id: Number(id), nome })
);
