export const TEMAS = {
  AVENTURA: { id: 1, descricao: "Aventura" },
  FANTASIA: { id: 2, descricao: "Fantasia" },
  LITERATURA: { id: 3, descricao: "Literatura" },
  MEDIEVAL: { id: 4, descricao: "Medieval" },
  FICCAO_CIENTIFICA: { id: 5, descricao: "Ficção Científica" },
  ECONOMIA_PRODUCAO: { id: 6, descricao: "Economia / Produção" },
  CIVILIZACAO: { id: 7, descricao: "Civilização" },
  TRANSPORTES: { id: 8, descricao: "Transportes" },
  MEIO_AMBIENTE: { id: 9, descricao: "Meio Ambiente" },
  CIENCIAS: { id: 10, descricao: "Ciências" },
  HORROR_TERROR: { id: 11, descricao: "Horror/Terror" },
  LUTA_ARTES_MARCIAIS: { id: 12, descricao: "Luta / Artes Marciais" },
  POLICIAL: { id: 13, descricao: "Policial" },
  QUADRINHOS: { id: 14, descricao: "Quadrinhos" },
  FAROESTE: { id: 15, descricao: "Faroeste" },
  ANIMAIS: { id: 16, descricao: "Animais" },
  POLITICA: { id: 17, descricao: "Política" },
  GUERRA: { id: 18, descricao: "Guerra" },
  HISTORIA: { id: 19, descricao: "História" },
  CULTURA_POP_OU_GEEK: { id: 20, descricao: "Cultura Pop ou Geek" },
  GENERICO_UNIVERSAL: { id: 21, descricao: "Genérico/Universal" },
  MITOLOGIA: { id: 22, descricao: "Mitologia" },
  EDUCACIONAL: { id: 23, descricao: "Educacional" },
  CULTURA_ORIENTAL: { id: 24, descricao: "Cultura Oriental" },
  VIKINGS: { id: 25, descricao: "Vikings" },
  ADULTO: { id: 26, descricao: "Adulto" },
  ESPORTES: { id: 27, descricao: "Esportes" },
  ARTE: { id: 28, descricao: "Arte" },
  HUMOR: { id: 29, descricao: "Humor" },
  PRE_HISTORICO: { id: 30, descricao: "Pré-Histórico" },
  CULTURA_BRASILEIRA: { id: 31, descricao: "Cultura Brasileira" },
  RELIGIAO: { id: 32, descricao: "Religião" },
  TEMA_DE_VIDEO_GAME: { id: 33, descricao: "Tema de Video Game" },
  GASTRONOMIA: { id: 34, descricao: "Gastronomia" },
  PIRATAS: { id: 35, descricao: "Piratas" },
  ANIME_MANGA: { id: 36, descricao: "Anime / Manga" },
  CULTURA_AFRICANA: { id: 37, descricao: "Cultura Africana" },
} as const;

export type TemaKey = keyof typeof TEMAS;
export type TemaInfo = (typeof TEMAS)[TemaKey];
export const TEMAS_LIST = Object.values(TEMAS);
