export const TEMAS_MAP = {
  1: "Aventura",
  2: "Fantasia",
  3: "Literatura",
  4: "Medieval",
  5: "Ficção Científica",
  6: "Economia / Produção",
  7: "Civilização",
  8: "Transportes",
  9: "Meio Ambiente",
  10: "Ciências",
  11: "Horror/Terror",
  12: "Luta / Artes Marciais",
  13: "Policial",
  14: "Quadrinhos",
  15: "Faroeste",
  16: "Animais",
  17: "Política",
  18: "Guerra",
  19: "História",
  20: "Cultura Pop ou Geek",
  21: "Genérico/Universal",
  22: "Mitologia",
  23: "Educacional",
  24: "Cultura Oriental",
  25: "Vikings",
  26: "Adulto",
  27: "Esportes",
  28: "Arte",
  29: "Humor",
  30: "Pré-Histórico",
  31: "Cultura Brasileira",
  32: "Religião",
  33: "Tema de Video Game",
  34: "Gastronomia",
  35: "Piratas",
  36: "Anime / Manga",
  37: "Cultura Africana",
} as const;

export type TemaId = keyof typeof TEMAS_MAP;

export const TEMAS_LIST = Object.entries(TEMAS_MAP).map(([id, nome]) => ({
  id: Number(id),
  nome,
}));
