
services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}
    restart: unless-stopped
